package com.kingodogo.buildscape.variantengine.block;

import com.kingodogo.buildscape.variantengine.builder.BlockShape;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraftforge.common.extensions.IForgeBlock;
import org.jetbrains.annotations.Nullable;

/**
 * Interface for blocks generated by the Variant Engine.
 */
public interface ExtShapeBlockInterface extends IForgeBlock {

    Block getBaseBlock();

    /**
     * Gets the shape of this block.
     */
    @Nullable
    default BlockShape getBlockShape() {
        return null;
    }

    @Override
    default int getFlammability(BlockState state, BlockGetter level, BlockPos pos, Direction direction) {
        final Block block = getBaseBlock();
        if (block != null) {
            if (state.hasProperty(BlockStateProperties.WATERLOGGED) && state.getValue(BlockStateProperties.WATERLOGGED)) {
                return 0;
            }
            return block.getFlammability(block.defaultBlockState(), level, pos, direction);
        } else {
            return IForgeBlock.super.getFlammability(state, level, pos, direction);
        }
    }

    @Override
    default int getFireSpreadSpeed(BlockState state, BlockGetter level, BlockPos pos, Direction direction) {
        final Block block = getBaseBlock();
        if (block != null) {
            if (state.hasProperty(BlockStateProperties.WATERLOGGED) && state.getValue(BlockStateProperties.WATERLOGGED)) {
                return 0;
            }
            return block.getFireSpreadSpeed(block.defaultBlockState(), level, pos, direction);
        } else {
            return IForgeBlock.super.getFireSpreadSpeed(state, level, pos, direction);
        }
    }

    @Override
    default boolean canEntityDestroy(BlockState state, BlockGetter level, BlockPos pos, Entity entity) {
        final Block block = getBaseBlock();
        if (block != null) {
            return block.canEntityDestroy(block.defaultBlockState(), level, pos, entity);
        } else {
            return IForgeBlock.super.canEntityDestroy(state, level, pos, entity);
        }
    }
}
