package com.kingodogo.buildscape.item;

import com.kingodogo.buildscape.BuildScape;
import net.minecraft.core.NonNullList;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class ModCreativeModeTab {

    public static final CreativeModeTab BUILDSCAPE_TAB = new CreativeModeTab(BuildScape.MODID) {
        @Override
        public ItemStack makeIcon() {
            return new ItemStack(ModItems.BIT_OXIDIZED_COPPER_BLOCK.get());
        }

        @Override
        public void fillItemList(NonNullList<ItemStack> items) {
            // 1. Gather ALL potential items for this tab
            NonNullList<ItemStack> rawList = NonNullList.create();
            addHardcodedItems(rawList);
            
            NonNullList<ItemStack> others = NonNullList.create();
            super.fillItemList(others);
            for (ItemStack stack : others) {
                if (!containsItem(rawList, stack.getItem())) {
                    rawList.add(stack);
                }
            }
            
            // 2. Clear target and intelligently rebuild it
            items.clear();
            Set<Item> added = new HashSet<>();
            
            for (ItemStack stack : rawList) {
                Item item = stack.getItem();
                if (added.contains(item)) continue;

                // Skip adding vertical variants here, they will be inserted next to their parents
                if (isGeneratedVertical(item)) continue;
                
                // Add the current item
                items.add(stack);
                added.add(item);

                // If this is a block, immediately insert its vertical variants right after it!
                if (item instanceof net.minecraft.world.item.BlockItem) {
                    Block block = ((net.minecraft.world.item.BlockItem)item).getBlock();
                    Block root = findRootBlock(block);
                    // Only expand from the root block to preserve ordering
                    if (block == root) {
                        insertFamilyVariants(items, added, block);
                    }
                }
            }
            
            // 3. Final safety pass for any orphan vertical blocks (e.g. from mods with weird names)
            appendRemainingVerticals(items, added);
        }

        private void insertFamilyVariants(NonNullList<ItemStack> items, Set<Item> added, Block base) {
            // Find the TRUE base of this family (e.g. if we are looking at Oak Slab, find Oak)
            Block root = com.kingodogo.buildscape.variantengine.family.BlockFamilyDetector.detectFamily(base) != null ? 
                         findRootBlock(base) : base;

            // Define the ideal sequence for building materials
            com.kingodogo.buildscape.variantengine.builder.BlockShape[] sequence = {
                com.kingodogo.buildscape.variantengine.builder.BlockShape.SLAB,
                com.kingodogo.buildscape.variantengine.builder.BlockShape.VERTICAL_SLAB,
                com.kingodogo.buildscape.variantengine.builder.BlockShape.STAIRS,
                com.kingodogo.buildscape.variantengine.builder.BlockShape.VERTICAL_STAIRS,
                com.kingodogo.buildscape.variantengine.builder.BlockShape.QUARTER_PIECE
            };

            for (com.kingodogo.buildscape.variantengine.builder.BlockShape shape : sequence) {
                Block variant = com.kingodogo.buildscape.variantengine.util.BlockBiMaps.getBlockOf(shape, root);
                if (variant != null && variant != net.minecraft.world.level.block.Blocks.AIR) {
                    ItemStack vStack = new ItemStack(variant);
                    if (added.add(vStack.getItem())) {
                        items.add(vStack);
                    }
                }
            }
        }

        private boolean isGeneratedVertical(Item item) {
            ResourceLocation id = item.getRegistryName();
            if (id == null) return false;
            String path = id.getPath();
            return id.getNamespace().equals(BuildScape.MODID) && (path.startsWith("v_slab_") || path.startsWith("v_stair_") || path.startsWith("q_piece_"));
        }

        private Block findRootBlock(Block block) {
            if (com.kingodogo.buildscape.variantengine.util.BlockBiMaps.BASE_BLOCKS.contains(block)) return block;
            
            // Check if it's a variant of a known base
            for (Block base : com.kingodogo.buildscape.variantengine.util.BlockBiMaps.BASE_BLOCKS) {
                if (isNormalVariantOf(block, base)) return base;
            }
            return block;
        }

        private boolean containsItem(List<ItemStack> list, Item item) {
            for (ItemStack s : list) if (s.getItem() == item) return true;
            return false;
        }

        private Block findVerticalVariant(Block block, com.kingodogo.buildscape.variantengine.builder.BlockShape shape) {
            // Strategy 1: Is this block itself a BASE block?
            if (com.kingodogo.buildscape.variantengine.util.BlockBiMaps.BASE_BLOCKS.contains(block)) {
                return com.kingodogo.buildscape.variantengine.util.BlockBiMaps.getBlockOf(shape, block);
            }
            
            // Strategy 2: Is this a slab/stair of a base block?
            // (e.g. block is Oak Slab, we want to find Oak Vertical Slab)
            for (Block base : com.kingodogo.buildscape.variantengine.util.BlockBiMaps.BASE_BLOCKS) {
                if (isNormalVariantOf(block, base)) {
                    return com.kingodogo.buildscape.variantengine.util.BlockBiMaps.getBlockOf(shape, base);
                }
            }
            return null;
        }

        private boolean isNormalVariantOf(Block block, Block base) {
             String bName = block.getRegistryName().getPath();
             String baseName = base.getRegistryName().getPath();
             // Simple heuristic: block contains base name and is a slab/stair
             return bName.contains(baseName) && (bName.contains("slab") || bName.contains("stair"));
        }

        private void appendRemainingVerticals(NonNullList<ItemStack> items, Set<Item> added) {
            for (Block base : com.kingodogo.buildscape.variantengine.util.BlockBiMaps.BASE_BLOCKS) {
                for (com.kingodogo.buildscape.variantengine.builder.BlockShape shape : 
                     new com.kingodogo.buildscape.variantengine.builder.BlockShape[]{
                         com.kingodogo.buildscape.variantengine.builder.BlockShape.VERTICAL_SLAB, 
                         com.kingodogo.buildscape.variantengine.builder.BlockShape.VERTICAL_STAIRS}) {
                    Block v = com.kingodogo.buildscape.variantengine.util.BlockBiMaps.getBlockOf(shape, base);
                    if (v != null && !added.contains(v.asItem())) {
                        items.add(new ItemStack(v));
                        added.add(v.asItem());
                    }
                }
            }
        }

private void addHardcodedItems(@NotNull NonNullList<ItemStack> items) {
            items.add(new ItemStack(ModItems.BIT_COPPER_BLOCK.get()));
            items.add(new ItemStack(ModItems.BIT_COPPER_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_COPPER_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_COPPER_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_CUT_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_CUT_COPPER_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_CUT_COPPER_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_CUT_COPPER_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_CHISELED_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_COPPER_BULB.get()));
            items.add(new ItemStack(ModItems.BIT_COPPER_GRATE.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_COPPER_BLOCK.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_COPPER_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_COPPER_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_COPPER_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_CUT_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_CUT_COPPER_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_CUT_COPPER_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_CUT_COPPER_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_CHISELED_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_COPPER_BULB.get()));
            items.add(new ItemStack(ModItems.BIT_EXPOSED_COPPER_GRATE.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_COPPER_BLOCK.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_COPPER_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_COPPER_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_COPPER_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_CUT_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_CUT_COPPER_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_CUT_COPPER_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_CUT_COPPER_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_CHISELED_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_COPPER_BULB.get()));
            items.add(new ItemStack(ModItems.BIT_WEATHERED_COPPER_GRATE.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_COPPER_BLOCK.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_COPPER_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_COPPER_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_COPPER_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_CUT_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_CUT_COPPER_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_CUT_COPPER_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_CUT_COPPER_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_CHISELED_COPPER.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_COPPER_BULB.get()));
            items.add(new ItemStack(ModItems.BIT_OXIDIZED_COPPER_GRATE.get()));
            items.add(new ItemStack(ModItems.COPPER_NUGGET.get()));
            items.add(new ItemStack(ModItems.COPPER_CHAIN.get()));
            items.add(new ItemStack(ModItems.EXPOSED_COPPER_CHAIN.get()));
            items.add(new ItemStack(ModItems.WEATHERED_COPPER_CHAIN.get()));
            items.add(new ItemStack(ModItems.OXIDIZED_COPPER_CHAIN.get()));
            items.add(new ItemStack(ModItems.STEEL_INGOT.get()));
            items.add(new ItemStack(ModItems.STEEL_BLOCK.get()));
            items.add(new ItemStack(ModItems.STEEL_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.STEEL_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.STEEL_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_STEEL.get()));
            items.add(new ItemStack(ModItems.POLISHED_STEEL_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_STEEL_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_STEEL_WALL.get()));
            items.add(new ItemStack(ModItems.PRESSED_STEEL.get()));
            items.add(new ItemStack(ModItems.PRESSED_STEEL_STAIRS.get()));
            items.add(new ItemStack(ModItems.PRESSED_STEEL_SLAB.get()));
            items.add(new ItemStack(ModItems.PRESSED_STEEL_WALL.get()));
            items.add(new ItemStack(ModItems.CUT_STEEL.get()));
            items.add(new ItemStack(ModItems.CUT_STEEL_STAIRS.get()));
            items.add(new ItemStack(ModItems.CUT_STEEL_SLAB.get()));
            items.add(new ItemStack(ModItems.CUT_STEEL_WALL.get()));
            items.add(new ItemStack(ModItems.FACTORY_STEEL_PANEL.get()));
            items.add(new ItemStack(ModItems.STEEL_CASING.get()));
            items.add(new ItemStack(ModItems.STEEL_TRIM.get()));
            items.add(new ItemStack(ModItems.STEEL_PILLAR.get()));
            items.add(new ItemStack(ModItems.BOLTED_STEEL_PILLAR.get()));
            items.add(new ItemStack(ModItems.STEEL_GRATE.get()));
            items.add(new ItemStack(ModItems.STEEL_FAN.get()));
            items.add(new ItemStack(ModItems.BLACK_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.BLACK_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.BLUE_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.BLUE_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.BROWN_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.BROWN_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.GRAY_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.GRAY_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.GREEN_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.GREEN_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.LIME_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.LIME_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.ORANGE_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.ORANGE_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.RED_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.RED_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.YELLOW_FACTORY_MESH.get()));
            items.add(new ItemStack(ModItems.YELLOW_FACTORY_MESH_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_FACTORY_MESH_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_FACTORY_MESH_WALL.get()));
            items.add(new ItemStack(ModItems.CAUTION_FACTORY.get()));
            items.add(new ItemStack(ModItems.CAUTION_FACTORY_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_FACTORY_SLAB.get()));
            items.add(new ItemStack(ModItems.FRAMED_CAUTION.get()));
            items.add(new ItemStack(ModItems.FRAMED_CAUTION_STAIRS.get()));
            items.add(new ItemStack(ModItems.FRAMED_CAUTION_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_BLACK.get()));
            items.add(new ItemStack(ModItems.CAUTION_BLACK_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_BLACK_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_WHITE.get()));
            items.add(new ItemStack(ModItems.CAUTION_WHITE_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_WHITE_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_RED.get()));
            items.add(new ItemStack(ModItems.CAUTION_RED_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_RED_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_BLUE.get()));
            items.add(new ItemStack(ModItems.CAUTION_BLUE_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_BLUE_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_YELLOW.get()));
            items.add(new ItemStack(ModItems.CAUTION_YELLOW_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_YELLOW_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_LIME.get()));
            items.add(new ItemStack(ModItems.CAUTION_LIME_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_LIME_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_PINK.get()));
            items.add(new ItemStack(ModItems.CAUTION_PINK_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_PINK_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_CANDY.get()));
            items.add(new ItemStack(ModItems.CAUTION_CANDY_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_CANDY_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_COTTONCANDY.get()));
            items.add(new ItemStack(ModItems.CAUTION_COTTONCANDY_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_COTTONCANDY_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_MINTCANDY.get()));
            items.add(new ItemStack(ModItems.CAUTION_MINTCANDY_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_MINTCANDY_SLAB.get()));
            items.add(new ItemStack(ModItems.CAUTION_CITRUSCANDY.get()));
            items.add(new ItemStack(ModItems.CAUTION_CITRUSCANDY_STAIRS.get()));
            items.add(new ItemStack(ModItems.CAUTION_CITRUSCANDY_SLAB.get()));
            items.add(new ItemStack(Items.CHAIN));
            items.add(new ItemStack(ModItems.LARGE_IRON_CHAIN.get()));
            items.add(new ItemStack(ModItems.ANCIENT_STEEL_CHAIN.get()));
            items.add(new ItemStack(ModItems.LARGE_ANCIENT_STEEL_CHAIN.get()));
            items.add(new ItemStack(ModItems.GOLD_CHAIN.get()));
            items.add(new ItemStack(ModItems.LARGE_GOLD_CHAIN.get()));
            items.add(new ItemStack(ModItems.DIAMOND_CHAIN.get()));
            items.add(new ItemStack(ModItems.LARGE_DIAMOND_CHAIN.get()));
            items.add(new ItemStack(ModItems.EMERALD_CHAIN.get()));
            items.add(new ItemStack(ModItems.LARGE_EMERALD_CHAIN.get()));
            items.add(new ItemStack(ModItems.NETHERITE_CHAIN.get()));
            items.add(new ItemStack(ModItems.LARGE_NETHERITE_CHAIN.get()));
            items.add(new ItemStack(ModItems.BIT_CHISELED_TUFF.get()));
            items.add(new ItemStack(ModItems.BIT_CHISELED_TUFF_BRICKS.get()));
            items.add(new ItemStack(ModItems.BIT_POLISHED_TUFF.get()));
            items.add(new ItemStack(ModItems.BIT_POLISHED_TUFF_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_POLISHED_TUFF_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_POLISHED_TUFF_WALL.get()));
            items.add(new ItemStack(ModItems.BIT_TUFF_BRICKS.get()));
            items.add(new ItemStack(ModItems.BIT_TUFF_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BIT_TUFF_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.BIT_TUFF_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.WHITE_TILES.get()));
            items.add(new ItemStack(ModItems.WHITE_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_TILES.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.GRAY_TILES.get()));
            items.add(new ItemStack(ModItems.GRAY_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.BLACK_TILES.get()));
            items.add(new ItemStack(ModItems.BLACK_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.BROWN_TILES.get()));
            items.add(new ItemStack(ModItems.BROWN_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.RED_TILES.get()));
            items.add(new ItemStack(ModItems.RED_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.ORANGE_TILES.get()));
            items.add(new ItemStack(ModItems.ORANGE_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.YELLOW_TILES.get()));
            items.add(new ItemStack(ModItems.YELLOW_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.LIME_TILES.get()));
            items.add(new ItemStack(ModItems.LIME_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.GREEN_TILES.get()));
            items.add(new ItemStack(ModItems.GREEN_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.CYAN_TILES.get()));
            items.add(new ItemStack(ModItems.CYAN_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.CYAN_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.CYAN_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_TILES.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.BLUE_TILES.get()));
            items.add(new ItemStack(ModItems.BLUE_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.PURPLE_TILES.get()));
            items.add(new ItemStack(ModItems.PURPLE_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.PURPLE_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.PURPLE_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.MAGENTA_TILES.get()));
            items.add(new ItemStack(ModItems.MAGENTA_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.MAGENTA_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.PINK_TILES.get()));
            items.add(new ItemStack(ModItems.PINK_TILES_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_TILES_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_TILES_WALL.get()));
            items.add(new ItemStack(ModItems.WHITE_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.WHITE_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.GRAY_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.GRAY_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.BLACK_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.BLACK_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.BROWN_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.BROWN_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.RED_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.RED_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.ORANGE_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.ORANGE_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.YELLOW_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.YELLOW_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.LIME_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.LIME_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.GREEN_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.GREEN_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.CYAN_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.CYAN_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.CYAN_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.CYAN_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.BLUE_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.BLUE_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.PURPLE_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.PURPLE_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PURPLE_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.PURPLE_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.PINK_STAINED_BRICKS.get()));
            items.add(new ItemStack(ModItems.PINK_STAINED_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_STAINED_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_STAINED_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK_FENCE.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.BAMBOO_BLOCK_BUTTON.get()));
            items.add(new ItemStack(ModItems.BAMBOO_WOOD.get()));
            items.add(new ItemStack(ModItems.BAMBOO_DOOR.get()));
            items.add(new ItemStack(ModItems.BAMBOO_TRAPDOOR.get()));
            items.add(new ItemStack(ModItems.BAMBOO_SIGN.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK_FENCE.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK_BUTTON.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_BLOCK_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BAMBOO_WOOD.get()));
            items.add(new ItemStack(ModItems.MANGROVE_LOG.get()));
            items.add(new ItemStack(ModItems.STRIPPED_MANGROVE_LOG.get()));
            items.add(new ItemStack(ModItems.MANGROVE_WOOD.get()));
            items.add(new ItemStack(ModItems.STRIPPED_MANGROVE_WOOD.get()));
            items.add(new ItemStack(ModItems.MANGROVE_LEAVES.get()));
            items.add(new ItemStack(ModItems.MANGROVE_ROOTS.get()));
            items.add(new ItemStack(ModItems.MUDDY_MANGROVE_ROOTS.get()));
            items.add(new ItemStack(ModItems.MUD.get()));
            items.add(new ItemStack(ModItems.MUD_SLAB.get()));
            items.add(new ItemStack(ModItems.PACKED_MUD.get()));
            items.add(new ItemStack(ModItems.PACKED_MUD_STAIRS.get()));
            items.add(new ItemStack(ModItems.PACKED_MUD_SLAB.get()));
            items.add(new ItemStack(ModItems.PACKED_MUD_WALL.get()));
            items.add(new ItemStack(ModItems.MUD_BRICKS.get()));
            items.add(new ItemStack(ModItems.MUD_BRICK_STAIRS.get()));
            items.add(new ItemStack(ModItems.MUD_BRICK_SLAB.get()));
            items.add(new ItemStack(ModItems.MUD_BRICK_WALL.get()));
            items.add(new ItemStack(ModItems.MANGROVE_PROPAGULE.get()));
            items.add(new ItemStack(ModItems.MANGROVE_PLANKS.get()));
            items.add(new ItemStack(ModItems.MANGROVE_STAIRS.get()));
            items.add(new ItemStack(ModItems.MANGROVE_SLAB.get()));
            items.add(new ItemStack(ModItems.MANGROVE_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.MANGROVE_FENCE.get()));
            items.add(new ItemStack(ModItems.MANGROVE_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.MANGROVE_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.MANGROVE_BUTTON.get()));
            items.add(new ItemStack(ModItems.MANGROVE_DOOR.get()));
            items.add(new ItemStack(ModItems.MANGROVE_TRAPDOOR.get()));
            items.add(new ItemStack(ModItems.MANGROVE_SIGN.get()));
            items.add(new ItemStack(ModItems.STRIPPED_MANGROVE_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.MANGROVE_BOAT.get()));
            items.add(new ItemStack(ModItems.OAK_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.STRIPPED_OAK_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.SPRUCE_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.STRIPPED_SPRUCE_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.BIRCH_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.STRIPPED_BIRCH_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.DARK_OAK_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.STRIPPED_DARK_OAK_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.JUNGLE_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.STRIPPED_JUNGLE_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.ACACIA_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.STRIPPED_ACACIA_WOOD_WALL.get()));
            items.add(new ItemStack(ModItems.ASHPEN_WHITE_PLANKS.get()));
            items.add(new ItemStack(ModItems.ASHPEN_WHITE_STAIRS.get()));
            items.add(new ItemStack(ModItems.ASHPEN_WHITE_SLAB.get()));
            items.add(new ItemStack(ModItems.ASHPEN_WHITE_BUTTON.get()));
            items.add(new ItemStack(ModItems.ASHPEN_WHITE_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.ASHPEN_WHITE_FENCE.get()));
            items.add(new ItemStack(ModItems.ASHPEN_WHITE_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.GRAY_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.GRAY_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.GRAY_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.GRAY_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.GRAY_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.BLACK_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.BLACK_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.BLACK_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.BLACK_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.BLACK_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.BROWN_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.BROWN_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.BROWN_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.BROWN_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.BROWN_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.RED_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.RED_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.RED_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.RED_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.RED_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.ORANGE_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.ORANGE_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.ORANGE_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.ORANGE_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.ORANGE_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.YELLOW_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.YELLOW_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.YELLOW_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.YELLOW_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.YELLOW_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.LIME_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.LIME_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.LIME_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.LIME_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.LIME_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.GREEN_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.GREEN_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.GREEN_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.GREEN_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.GREEN_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.CYAN_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.CYAN_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.CYAN_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.CYAN_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.CYAN_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.CYAN_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.CYAN_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.BLUE_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.BLUE_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.BLUE_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.BLUE_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.BLUE_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.PURPLE_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.PURPLE_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.PURPLE_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.PURPLE_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.PURPLE_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.PURPLE_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.PURPLE_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.PINK_ASHPEN_PLANKS.get()));
            items.add(new ItemStack(ModItems.PINK_ASHPEN_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_ASHPEN_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_ASHPEN_BUTTON.get()));
            items.add(new ItemStack(ModItems.PINK_ASHPEN_PRESSURE_PLATE.get()));
            items.add(new ItemStack(ModItems.PINK_ASHPEN_FENCE.get()));
            items.add(new ItemStack(ModItems.PINK_ASHPEN_FENCE_GATE.get()));
            items.add(new ItemStack(ModItems.WHITE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.GRAY_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.BLACK_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.BROWN_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.RED_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.ORANGE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.YELLOW_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.LIME_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.GREEN_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.CYAN_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.CYAN_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.CYAN_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.BLUE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.PURPLE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.PURPLE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.PURPLE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.MAGENTA_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.MAGENTA_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.PINK_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_WHITE_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_WHITE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_WHITE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_WHITE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_GRAY_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_GRAY_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_GRAY_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_GRAY_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_GRAY_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_GRAY_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_GRAY_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_GRAY_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLACK_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLACK_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLACK_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLACK_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_BROWN_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_BROWN_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_BROWN_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_BROWN_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_RED_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_RED_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_RED_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_RED_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_ORANGE_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_ORANGE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_ORANGE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_ORANGE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_YELLOW_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_YELLOW_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_YELLOW_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_YELLOW_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIME_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIME_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIME_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIME_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_GREEN_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_GREEN_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_GREEN_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_GREEN_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_CYAN_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_CYAN_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_CYAN_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_CYAN_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_BLUE_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_BLUE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_BLUE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_LIGHT_BLUE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLUE_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLUE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLUE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_BLUE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_PURPLE_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_PURPLE_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_PURPLE_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_PURPLE_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_MAGENTA_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_MAGENTA_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_MAGENTA_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_MAGENTA_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_PINK_CONCRETE.get()));
            items.add(new ItemStack(ModItems.POLISHED_PINK_CONCRETE_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_PINK_CONCRETE_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_PINK_CONCRETE_WALL.get()));
            items.add(new ItemStack(ModItems.WHITE_SAND.get()));
            items.add(new ItemStack(ModItems.WHITE_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.WHITE_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.WHITE_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.WHITE_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.BLACK_SAND.get()));
            items.add(new ItemStack(ModItems.BLACK_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.BLACK_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.BLACK_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.BLACK_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.RED_SAND.get()));
            items.add(new ItemStack(ModItems.RED_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.RED_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.RED_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.RED_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.ORANGE_SAND.get()));
            items.add(new ItemStack(ModItems.ORANGE_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.ORANGE_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.ORANGE_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.ORANGE_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.YELLOW_SAND.get()));
            items.add(new ItemStack(ModItems.YELLOW_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.YELLOW_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.YELLOW_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.YELLOW_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.GREEN_SAND.get()));
            items.add(new ItemStack(ModItems.GREEN_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.GREEN_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.GREEN_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.GREEN_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.BLUE_SAND.get()));
            items.add(new ItemStack(ModItems.BLUE_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.BLUE_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.BLUE_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.BLUE_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.PINK_SAND.get()));
            items.add(new ItemStack(ModItems.PINK_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.PINK_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.PINK_SMOOTH_SANDSTONE.get()));
            items.add(new ItemStack(ModItems.PINK_SMOOTH_SANDSTONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_SMOOTH_SANDSTONE_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.WHITE_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.WHITE_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.GRAY_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.GRAY_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.BLACK_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.BLACK_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.BROWN_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.BROWN_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.RED_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.RED_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.ORANGE_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.ORANGE_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.YELLOW_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.YELLOW_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.LIME_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.LIME_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.GREEN_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.GREEN_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.CYAN_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.CYAN_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.CYAN_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.CYAN_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.BLUE_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.BLUE_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.PURPLE_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.PURPLE_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.PURPLE_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PURPLE_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.MAGENTA_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.MAGENTA_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.PINK_MOSAIC_GLASS.get()));
            items.add(new ItemStack(ModItems.PINK_MOSAIC_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_MOSAIC_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_MOSAIC_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_WHITE_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_WHITE_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_WHITE_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_WHITE_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_GRAY_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_GRAY_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_GRAY_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_GRAY_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_GRAY_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_GRAY_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_GRAY_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_GRAY_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLACK_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLACK_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLACK_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLACK_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_BROWN_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_BROWN_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_BROWN_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_BROWN_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_RED_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_RED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_RED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_RED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_ORANGE_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_ORANGE_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_ORANGE_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_ORANGE_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_YELLOW_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_YELLOW_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_YELLOW_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_YELLOW_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIME_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIME_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIME_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIME_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_GREEN_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_GREEN_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_GREEN_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_GREEN_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_CYAN_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_CYAN_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_CYAN_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_CYAN_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_BLUE_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_BLUE_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_BLUE_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_LIGHT_BLUE_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLUE_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLUE_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLUE_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_BLUE_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_PURPLE_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_PURPLE_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_PURPLE_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_PURPLE_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_MAGENTA_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_MAGENTA_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_MAGENTA_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_MAGENTA_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.FACTORY_PINK_GLASS.get()));
            items.add(new ItemStack(ModItems.FACTORY_PINK_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.FACTORY_PINK_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.FACTORY_PINK_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.WHITE_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.WHITE_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.GRAY_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.GRAY_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.BLACK_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.BLACK_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.BROWN_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.BROWN_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.RED_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.RED_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.ORANGE_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.ORANGE_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.YELLOW_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.YELLOW_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.LIME_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.LIME_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.GREEN_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.GREEN_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.CYAN_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.CYAN_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.CYAN_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.CYAN_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.BLUE_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.BLUE_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.PURPLE_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.PURPLE_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.PURPLE_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PURPLE_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.MAGENTA_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.MAGENTA_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.PINK_GLAZED_GLASS.get()));
            items.add(new ItemStack(ModItems.PINK_GLAZED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_GLAZED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_GLAZED_GLASS_PANE.get()));
            items.add(new ItemStack(ModItems.GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.WHITE_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GRAY_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.GRAY_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLACK_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLACK_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BROWN_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BROWN_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.RED_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.RED_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.ORANGE_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.ORANGE_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.YELLOW_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.YELLOW_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIME_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIME_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.GREEN_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.GREEN_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.CYAN_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.CYAN_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.BLUE_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.BLUE_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PURPLE_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.PURPLE_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.PINK_STAINED_GLASS_SLAB.get()));
            items.add(new ItemStack(ModItems.PINK_STAINED_GLASS_STAIRS.get()));
            items.add(new ItemStack(ModItems.WHITE_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.ORANGE_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.YELLOW_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.LIME_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.PINK_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.GRAY_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.CYAN_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.PURPLE_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.BLUE_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.BROWN_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.GREEN_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.RED_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.BLACK_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.GLASS_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.TINTED_GLASS_ORNAMENT.get()));
            items.add(new ItemStack(ModItems.GLOW_STAR.get()));
            items.add(new ItemStack(ModItems.WHITE_STAR.get()));
            items.add(new ItemStack(ModItems.ORANGE_STAR.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STAR.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STAR.get()));
            items.add(new ItemStack(ModItems.YELLOW_STAR.get()));
            items.add(new ItemStack(ModItems.LIME_STAR.get()));
            items.add(new ItemStack(ModItems.PINK_STAR.get()));
            items.add(new ItemStack(ModItems.GRAY_STAR.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STAR.get()));
            items.add(new ItemStack(ModItems.CYAN_STAR.get()));
            items.add(new ItemStack(ModItems.PURPLE_STAR.get()));
            items.add(new ItemStack(ModItems.BLUE_STAR.get()));
            items.add(new ItemStack(ModItems.BROWN_STAR.get()));
            items.add(new ItemStack(ModItems.GREEN_STAR.get()));
            items.add(new ItemStack(ModItems.RED_STAR.get()));
            items.add(new ItemStack(ModItems.BLACK_STAR.get()));
            items.add(new ItemStack(ModItems.WHITE_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.ORANGE_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.MAGENTA_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.YELLOW_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.LIME_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.PINK_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.GRAY_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.CYAN_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.PURPLE_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.BLUE_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.BROWN_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.GREEN_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.RED_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.BLACK_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.MULTICOLOR_STRING_LIGHT.get()));
            items.add(new ItemStack(ModItems.GLOW_LIGHTS.get()));
            items.add(new ItemStack(ModItems.MULTICOLOR_GLOW_LIGHTS.get()));
            items.add(new ItemStack(ModItems.FESTIVE_LAMP.get()));
            items.add(new ItemStack(ModItems.WHITE_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.GRAY_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.BLACK_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.BROWN_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.RED_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.ORANGE_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.YELLOW_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.LIME_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.GREEN_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.CYAN_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.BLUE_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.PURPLE_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.MAGENTA_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.PINK_REDSTONE_LAMP.get()));
            items.add(new ItemStack(ModItems.DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.WHITE_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.GRAY_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.BLACK_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.BROWN_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.RED_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.ORANGE_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.YELLOW_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.LIME_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.GREEN_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.CYAN_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.BLUE_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.PURPLE_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.MAGENTA_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.PINK_DECORATED_POT.get()));
            items.add(new ItemStack(ModItems.FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.WHITE_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.GRAY_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.BLACK_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.BROWN_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.RED_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.ORANGE_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.YELLOW_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.LIME_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.GREEN_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.CYAN_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.BLUE_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.PURPLE_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.MAGENTA_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.PINK_FESTIVE_STOCKING.get()));
            items.add(new ItemStack(ModItems.WHITE_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.GRAY_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.BLACK_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.BROWN_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.RED_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.ORANGE_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.YELLOW_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.LIME_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.GREEN_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.CYAN_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.BLUE_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.PURPLE_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.MAGENTA_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.PINK_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.INVISIBLE_ITEM_FRAME.get()));
            items.add(new ItemStack(ModItems.STONE_PILLAR.get()));
            items.add(new ItemStack(ModItems.MOSSY_PILLAR.get()));
            items.add(new ItemStack(ModItems.DEEPSLATE_PILLAR.get()));
            items.add(new ItemStack(ModItems.QUARTZ_PILLAR.get()));
            items.add(new ItemStack(ModItems.ASHENKING_DIAMOND_PILLAR.get()));
            items.add(new ItemStack(ModItems.ASHENKING_GOLD_PILLAR.get()));
            items.add(new ItemStack(ModItems.ASHENKING_EMERALD_PILLAR.get()));
            items.add(new ItemStack(ModItems.ASHENKING_NETHERITE_PILLAR.get()));
            items.add(new ItemStack(ModItems.ANCIENT_ASHEN_SCROLL.get()));
            items.add(new ItemStack(ModItems.SMOKE_VENT.get()));
            items.add(new ItemStack(ModItems.CASCADE_BLOCK.get()));
            items.add(new ItemStack(ModItems.CASCADE_BLOCK_NO_MIST.get()));
            items.add(new ItemStack(ModItems.BOTTLE_OF_MIST.get()));
            items.add(new ItemStack(ModItems.WHITE_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.LIGHT_GRAY_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.GRAY_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.BLACK_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.BROWN_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.RED_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.ORANGE_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.YELLOW_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.LIME_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.GREEN_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.CYAN_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.BLUE_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.PURPLE_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.MAGENTA_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.PINK_CARPET_LAYERS.get()));
            items.add(new ItemStack(ModItems.OAK_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SPRUCE_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.BIRCH_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.JUNGLE_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.ACACIA_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.DARK_OAK_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.AZALEA_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.FLOWERING_AZALEA_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.MANGROVE_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_OAK_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_SPRUCE_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_BIRCH_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_JUNGLE_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_ACACIA_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_DARK_OAK_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_MANGROVE_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_AZALEA_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.SNOWY_FLOWERING_AZALEA_LEAF_LAYERS.get()));
            items.add(new ItemStack(ModItems.OAK_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SPRUCE_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.BIRCH_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.JUNGLE_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.ACACIA_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.DARK_OAK_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.AZALEA_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.FLOWERING_AZALEA_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.MANGROVE_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_OAK_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_SPRUCE_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_BIRCH_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_JUNGLE_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_ACACIA_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_DARK_OAK_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_MANGROVE_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_AZALEA_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_FLOWERING_AZALEA_LEAF_HEDGE.get()));
            items.add(new ItemStack(ModItems.SNOWY_OAK_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_SPRUCE_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_BIRCH_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_JUNGLE_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_ACACIA_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_DARK_OAK_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_MANGROVE_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_AZALEA_LEAVES.get()));
            items.add(new ItemStack(ModItems.SNOWY_FLOWERING_AZALEA_LEAVES.get()));
            items.add(new ItemStack(ModItems.RED_ROSE_VINES.get()));
            items.add(new ItemStack(ModItems.BLACK_ROSE_VINES.get()));
            items.add(new ItemStack(ModItems.BLUE_ROSE_VINES.get()));
            items.add(new ItemStack(ModItems.WHITE_ROSE_VINES.get()));
            items.add(new ItemStack(ModItems.RED_MONETS.get()));
            items.add(new ItemStack(ModItems.BLUE_MONETS.get()));
            items.add(new ItemStack(ModItems.PURPLE_MONETS.get()));
            items.add(new ItemStack(ModItems.LIGHT_BLUE_MONETS.get()));
            items.add(new ItemStack(ModItems.PINK_MONETS.get()));
            items.add(new ItemStack(ModItems.YELLOW_MONETS.get()));
            items.add(new ItemStack(ModItems.RED_PETAL.get()));
            items.add(new ItemStack(ModItems.BLUE_PETAL.get()));
            items.add(new ItemStack(ModItems.ORANGE_PETAL.get()));
            items.add(new ItemStack(ModItems.PINK_PETAL.get()));
            items.add(new ItemStack(ModItems.PURPLE_PETAL.get()));
            items.add(new ItemStack(ModItems.CLOVER.get()));
            items.add(new ItemStack(ModItems.SNOWY_SHORT_GRASS.get()));
            items.add(new ItemStack(ModItems.SNOWY_TALL_GRASS.get()));
            items.add(new ItemStack(ModItems.SNOWY_FERN.get()));
            items.add(new ItemStack(ModItems.SNOWY_LARGE_FERN.get()));
            items.add(new ItemStack(ModItems.SNOWY_BUSH.get()));
            items.add(new ItemStack(ModItems.FROST_ROSE.get()));
            items.add(new ItemStack(ModItems.RED_SPORE_BLOSSOM.get()));
            items.add(new ItemStack(ModItems.CYAN_SPORE_BLOSSOM.get()));
            items.add(new ItemStack(ModItems.BLUE_SPORE_BLOSSOM.get()));
            items.add(new ItemStack(ModItems.PURPLE_SPORE_BLOSSOM.get()));
            items.add(new ItemStack(ModItems.ORANGE_SPORE_BLOSSOM.get()));
            items.add(new ItemStack(ModItems.BROWN_MUSHROOM_SHELVES.get()));
            items.add(new ItemStack(ModItems.RED_MUSHROOM_SHELVES.get()));
            items.add(new ItemStack(ModItems.CALCITE_STAIRS.get()));
            items.add(new ItemStack(ModItems.CALCITE_SLAB.get()));
            items.add(new ItemStack(ModItems.CALCITE_WALL.get()));
            items.add(new ItemStack(ModItems.MOSSY_CALCITE.get()));
            items.add(new ItemStack(ModItems.MOSSY_CALCITE_STAIRS.get()));
            items.add(new ItemStack(ModItems.MOSSY_CALCITE_SLAB.get()));
            items.add(new ItemStack(ModItems.MOSSY_CALCITE_WALL.get()));
            items.add(new ItemStack(ModItems.MOSS_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.MOSS_LAYERS.get()));
            items.add(new ItemStack(ModItems.MOSS_OVERLAY.get()));
            items.add(new ItemStack(ModItems.SNOW_STAIRS.get()));
            items.add(new ItemStack(ModItems.SNOW_SLAB.get()));
            items.add(new ItemStack(ModItems.SNOW_OVERLAY.get()));
            items.add(new ItemStack(ModItems.SNOW_BRICKS.get()));
            items.add(new ItemStack(ModItems.SNOW_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.SNOW_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.SNOW_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.SNOWY_GRASS_BLOCK.get()));
            items.add(new ItemStack(ModItems.SNOWY_GRASS_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.SNOWY_GRASS_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.ICICLE.get()));
            items.add(new ItemStack(ModItems.ICICLE_BLOCK.get()));
            items.add(new ItemStack(ModItems.PACKED_ICICLE_BLOCK.get()));
            items.add(new ItemStack(ModItems.PODZOL_SLAB.get()));
            items.add(new ItemStack(ModItems.MYCELIUM_SLAB.get()));
            items.add(new ItemStack(ModItems.DIRT_SLAB.get()));
            items.add(new ItemStack(ModItems.AMETHYST_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.HAY_BALE_SLAB.get()));
            items.add(new ItemStack(ModItems.DRIPSTONE_BLOCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.DRIPSTONE_BLOCK_SLAB.get()));
            items.add(new ItemStack(ModItems.DRIPSTONE_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.POLISHED_BASALT_STAIRS.get()));
            items.add(new ItemStack(ModItems.POLISHED_BASALT_SLAB.get()));
            items.add(new ItemStack(ModItems.POLISHED_BASALT_WALL.get()));
            items.add(new ItemStack(ModItems.SMOOTH_BASALT_STAIRS.get()));
            items.add(new ItemStack(ModItems.SMOOTH_BASALT_SLAB.get()));
            items.add(new ItemStack(ModItems.END_STONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.END_STONE_SLAB.get()));
            items.add(new ItemStack(ModItems.END_STONE_WALL.get()));
            items.add(new ItemStack(ModItems.QUARTZ_BLOCK_WALL.get()));
            items.add(new ItemStack(ModItems.SMOOTH_QUARTZ_WALL.get()));
            items.add(new ItemStack(ModItems.QUARTZ_PILLAR_STAIRS.get()));
            items.add(new ItemStack(ModItems.QUARTZ_PILLAR_SLAB.get()));
            items.add(new ItemStack(ModItems.QUARTZ_PILLAR_WALL.get()));
            items.add(new ItemStack(ModItems.QUARTZ_BRICKS_STAIRS.get()));
            items.add(new ItemStack(ModItems.QUARTZ_BRICKS_SLAB.get()));
            items.add(new ItemStack(ModItems.QUARTZ_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.SMOOTH_SANDSTONE_WALL.get()));
            items.add(new ItemStack(ModItems.PRISMARINE_BRICKS_WALL.get()));
            items.add(new ItemStack(ModItems.DARK_PRISMARINE_WALL.get()));
            items.add(new ItemStack(ModItems.STONE_WALL.get()));
            items.add(new ItemStack(ModItems.SMOOTH_STONE_STAIRS.get()));
            items.add(new ItemStack(ModItems.BEDROCK_STAIRS.get()));
            items.add(new ItemStack(ModItems.BEDROCK_SLAB.get()));
            items.add(new ItemStack(ModItems.BEDROCK_WALL.get()));
            items.add(new ItemStack(ModItems.BEDROCK_PANE.get()));
            items.add(new ItemStack(ModItems.OBSIDIAN_STAIRS.get()));
            items.add(new ItemStack(ModItems.OBSIDIAN_SLAB.get()));
            items.add(new ItemStack(ModItems.BIG_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_WHITE_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_LIGHT_GRAY_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_GRAY_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_BLACK_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_BROWN_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_RED_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_ORANGE_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_YELLOW_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_LIME_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_GREEN_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_CYAN_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_LIGHT_BLUE_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_BLUE_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_PURPLE_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_MAGENTA_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_PINK_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_AMETHYST_CANDLE.get()));
            items.add(new ItemStack(ModItems.BIG_SCULK_CANDLE.get()));
        }
    };
}
